---

  - name: Pre-requisites for ElasticSearch (Ubuntu)
    apt:
      name:
        - openjdk-11-jdk
        - apt-transport-https
        - curl
        - gpgv
        - gpgsm
        - gnupg-l10n
        - gnupg
        - dirmngr
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Getting GPG Key (Ubuntu)
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Install ElasticSearch repository  (Ubuntu)
    apt_repository:
      repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      state: present
    when: ansible_distribution == "Ubuntu"


#  - name: Install ElasticSearch (Ubuntu)
#    apt:
#      name: elasticsearch
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"


  - name: Changing cluster name (Ubuntu)
    lineinfile:
      dest: /etc/elasticsearch/elasticsearch.yml
      line: "cluster.name: demo-elk"
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Cluster's descriptive name (Ubuntu)
    lineinfile:
      dest: /etc/elasticsearch/elasticsearch.yml
      line: "node.name: elk-1"
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Adding network.host (Ubuntu)
    lineinfile:
      dest: /etc/elasticsearch/elasticsearch.yml
      line: "network.host: 0.0.0.0"
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Adding http.port (Ubuntu)
    lineinfile:
      dest: /etc/elasticsearch/elasticsearch.yml
      line: "http.port: 9200"
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Adding discovery.type (Ubuntu)
    lineinfile:
      dest: /etc/elasticsearch/elasticsearch.yml
      line: "discovery.type: single-node"
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Creating an empty file for startup-timeout.conf - 1 (Ubuntu)
    file:
      path: "/etc/systemd/system/elasticsearch.service.d"
      state: directory
    when: ansible_distribution == "Ubuntu"

  - name: Creating an empty file for startup-timeout.conf - 2 (Ubuntu)
    file:
      path: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
      state: touch
    when: ansible_distribution == "Ubuntu"

  - name: Preventing service timeout (Ubuntu)
    copy:
      dest: "/etc/systemd/system/elasticsearch.service.d/startup-timeout.conf"
      content: |
        [Service]
        TimeoutStartSec=3min
    when: ansible_distribution == "Ubuntu"

  - name: Daemon-reload for ElasticSearch (Ubuntu)
    systemd: daemon_reload=yes
    when: ansible_distribution == "Ubuntu"

  - name: Enabling service, making sure it is not masked (Ubuntu)
    systemd:
      name: elasticsearch
      enabled: yes
      masked: no
    when: ansible_distribution == "Ubuntu"

#  - name: Starting ElasticSearch (Ubuntu)
#    systemd: state=started name=elasticsearch
#    when: ansible_distribution == "Ubuntu"

